### ISSUE TITLE
Make folder links resolve to the index.wiki file

### ISSUE THREAD

**Issue by jgilchrist** [lervag/wiki#3]
## Description

Given the following folder structure:

```
~/wiki
├── index.wiki
└── subfolder
    └── index.wiki
```

With the top-level index.wiki:

```
[[subfolder/]]
```

Navigating through this link goes to `~/wiki/subfolder/.wiki`. However, it seems like the intention is that it should navigate to `~/wiki/subfolder/index.wiki`.

My current workaround is to have the link read: `[[Refactoring/index|Refactoring/]]`.

**Comment by lervag** [comment]
Thanks! I've fixed this now. I also removed the warning about directories not existing and instead use `mkdir()` to create missing directories. I think it should be safe, as wiki links should always be "internal" to the wiki.

**Comment by jgilchrist** [comment]
Hi @lervag, thanks so much for such a quick response! The links are working great now - the only thing I noticed is that the top-level index of the wiki is now preceded by two forward slashes after I navigate to it with `<leader>ww`, e.g.

```
~/.vim/wiki//index.wiki
```

**Comment by lervag** [comment]
No problem! I'm happy to see someone else is using the plugin. :)

I don't see how to reproduce the issue with `<leader>ww`. Could you explain what you do to see the issue?

Btw: I have not really used subfolders myself, thus I can't guarantee that everything works as expected with subfolders. Feel free to open issues if you should find more problems related to this.
